name: schedule update data

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '1 12 * * 1'
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: generate new build
        run: |
          npm install
          npm run generate
          CI=false npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs # The folder the action should deploy.
          commit-message: "chore: publish with new data"
          # files: docs/
          # name: Github Action
          # email: 41898282+github-actions[bot]@users.noreply.github.com
          git-config-name: Github Action
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
